
spring: 
  datasource: 
    driverClassName: com.mysql.jdbc.Driver
    password: root
    url: "jdbc:mysql://34.105.221.119:3306/pricing_database?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    username: root
  
server:
   port: 8081